logging:
  file: logs/condenser-it2.log

spring:
  jmx:
    port: 49010
  data:
    elasticsearch:
      repositories:
        enabled: false

security:
  basic:
    enabled: false

server:
  port: 48010

infrastructure:
  environment-name: it2
  amqp-camel-component: stub
  amqp-server: localhost:5672
  amqp-ticks-exchange: turbine.it.market.ticks
  amqp-indicators-exchange: turbine.it.market.indicators
  amqp-strategies-exchange: turbine.it.market.strategies
  amqp-ticks-queue: turbine.it.queue.ticks
  amqp-indicators-queue: turbine.it.queue.indicators
  amqp-strategies-queue: turbine.it.queue.strategies
  elasticsearch-camel-component: stub
  elasticsearch-cluster: elasticsearch-test
  elasticsearch-host: localhost
  elasticsearch-native-port: 9305
  elasticsearch-rest-port: 9205
  elasticsearch-index-for-ticks: turbine-ticks-test
  elasticsearch-index-for-indicators: turbine-indicators-test
  elasticsearch-index-for-strategies: turbine-strategies-test
  elasticsearch-type-for-ticks: turbine-tick-test
  elasticsearch-type-for-indicators: turbine-indicator-test
  elasticsearch-type-for-strategies: turbine-strategy-test
  websocket-camel-component: stub
  websocket-ticks: /topic/ticks
  websocket-indicators: /topic/indicators
  websocket-strategies: /topic/strategies
  websocket-reply: /topic/reply
  
  
