logging:
  file: logs/condenser.log
spring:
  jmx:
    port: 49002
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      repositories:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest  
server:
  port: 48002
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: changeit
#    keyStoreType: PKCS12
#    keyAlias: tomcat
infrastructure:
  environment-name: test1
  amqp-camel-component: rabbitmq
  amqp-server: localhost:5672
  amqp-ticks-exchange: turbine.test1.market.ticks
  amqp-indicators-exchange: turbine.test1.market.indicators
  amqp-strategies-exchange: turbine.test1.market.strategies
  amqp-ticks-queue: turbine.test1.queue.ticks
  amqp-indicators-queue: turbine.test1.queue.indicators
  amqp-strategies-queue: turbine.test1.queue.strategies
  elasticsearch-camel-component: elasticsearch
  elasticsearch-cluster: elasticsearch
  elasticsearch-host: localhost
  elasticsearch-native-port: 9300
  elasticsearch-rest-port: 9200
  elasticsearch-index-for-ticks: turbine-ticks
  elasticsearch-index-for-indicators: turbine-indicators
  elasticsearch-index-for-strategies: turbine-strategies
  elasticsearch-type-for-ticks: turbine-tick
  elasticsearch-type-for-indicators: turbine-indicator
  elasticsearch-type-for-strategies: turbine-strategy
  websocket-camel-component: ssm
  websocket-ticks: /topic/ticks
  websocket-indicators: /topic/indicators
  websocket-strategies: /topic/strategies
  websocket-reply: /topic/reply
 