logging:
  file: logs/inlet.log
spring:
  jmx:
    port: 49006
server:
  port: 48006
exchanges:
  lse:
    companies:
      file: list-of-all-companies.xls
      url: http://www.londonstockexchange.com/statistics/companies-and-issuers/${markets.lse.companies.file}
    securities:
      file: list-of-all-securities-ex-debt.xls
      url: http://www.londonstockexchange.com/statistics/companies-and-issuers/${markets.lse.securities.file}