logging:
  file: logs/furnace.log
spring:
  jmx:
    port: 49009
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      repositories:
        enabled: false
server:
  port: 48009
  
infrastructure:
  environment-name: test1
  amqp-camel-component: rabbitmq
  amqp-server: localhost:5672
  amqp-ticks-exchange: turbine.test1.market.ticks
  amqp-ticks-queue: turbine.test1.queue.ticks
  elasticsearch-cluster: elasticsearch
  elasticsearch-host: localhost
  elasticsearch-native-port: 9300
  elasticsearch-rest-port: 9200
  elasticsearch-index-for-ticks: turbine-ticks
  elasticsearch-index-for-indicators: turbine-indicators
  elasticsearch-index-for-strategies: turbine-strategies
  elasticsearch-type-for-ticks: turbine-tick
  elasticsearch-type-for-indicators: turbine-indicator
  elasticsearch-type-for-strategies: turbine-strategy
  
